export const ALL_MODULES = [
  {
    id: 'dashboard',
    name: 'Dashboard',
    icon: 'FiHome',
    path: '/dashboard',
    permission: 'view_dashboard',
    roles: ['super_admin', 'sub_admin', 'seller', 'seller_employee'],
    order: 1,
  },
  {
    id: 'users',
    name: 'Users',
    icon: 'FiUsers',
    path: '/users',
    permission: 'manage_users',
    roles: ['super_admin'],
    order: 2,
  },
  {
    id: 'sellers',
    name: 'Sellers',
    icon: 'FiShoppingBag',
    path: '/sellers',
    permission: 'manage_sellers',
    roles: ['super_admin', 'sub_admin'],
    order: 3,
  },
  {
    id: 'products',
    name: 'Products',
    icon: 'FiPackage',
    path: '/products',
    permission: 'manage_products',
    roles: ['super_admin', 'sub_admin', 'seller'],
    order: 4,
  },
  {
    id: 'categories',
    name: 'Categories',
    icon: 'FiGrid',
    path: '/categories',
    permission: 'manage_categories',
    roles: ['super_admin', 'sub_admin'],
    order: 5,
  },
  {
    id: 'orders',
    name: 'Orders',
    icon: 'FiShoppingCart',
    path: '/orders',
    permission: 'manage_orders',
    roles: ['super_admin', 'sub_admin', 'seller', 'seller_employee'],
    order: 6,
  },
  {
    id: 'payments',
    name: 'Payments',
    icon: 'FiCreditCard',
    path: '/payments',
    permission: 'manage_payments',
    roles: ['super_admin', 'sub_admin'],
    order: 7,
  },
  {
    id: 'reviews',
    name: 'Reviews',
    icon: 'FiStar',
    path: '/reviews',
    permission: 'manage_reviews',
    roles: ['super_admin', 'sub_admin'],
    order: 8,
  },
  {
    id: 'reports',
    name: 'Reports',
    icon: 'FiBarChart2',
    path: '/reports',
    permission: 'view_reports',
    roles: ['super_admin', 'sub_admin', 'seller'],
    order: 9,
  },
  {
    id: 'roles',
    name: 'Roles & Permissions',
    icon: 'FiShield',
    path: '/roles',
    permission: 'manage_roles',
    roles: ['super_admin'],
    order: 10,
  },
  {
    id: 'notifications',
    name: 'Notifications',
    icon: 'FiBell',
    path: '/notifications',
    permission: 'manage_notifications',
    roles: ['super_admin', 'sub_admin'],
    order: 11,
  },
  {
    id: 'settings',
    name: 'Settings',
    icon: 'FiSettings',
    path: '/settings',
    permission: 'manage_settings',
    roles: ['super_admin'],
    order: 12,
  },
  {
    id: 'profile',
    name: 'Profile',
    icon: 'FiUser',
    path: '/profile',
    permission: 'view_profile',
    roles: ['super_admin', 'sub_admin', 'seller', 'seller_employee', 'customer'],
    order: 13,
  },
];